version: '3.8'

services:
  redis-voting:
    image: redis:7-alpine
    container_name: redis-voting-local
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"] # Activa AOF para persistencia
    networks:
      - voting-net

networks:
  voting-net:
    driver: bridge

volumes:
  redis_data: